### ISSUE TITLE
enclitic que

### ISSUE THREAD

**Issue by gcelano** [UniversalDependencies/UD_Latin-ITTB#4]
I see that enclitic _que_ is not attached to the previous word in "# text", as one should expect, but treated as a separate token (and accordingly no _SpaceAfter=No_) (the same in la_perseus): why is that?

**Comment by Stormur** [comment]
This situtation at the moment is just the outcome of the legacy conversion, where all syntactic words are considered independent tokens, process and has to be considered temporary. Since all the needed information is available in the original treebank, the formatting of multiword tokens (such as _xxx_+_que_, or +_ue_, etc.) will be addressed in the next release!
